#!/usr/bin/env python3
"""Regenerate the All Documents list in docs/INDEX.md from doc frontmatter.

Reads title / optional description / keywords / order from YAML-like
frontmatter at the top of each docs/**/*.md file. Does not write
frontmatter back into docs -- if a doc is missing a title, fix that file.

Usage (from repo root):
    python3 scripts/update-docs-index.py
    python3 scripts/update-docs-index.py --check
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

DOCS_DIR = Path("docs")
INDEX_FILE = DOCS_DIR / "INDEX.md"
MARKER_START = (
    "<!-- AUTO-GENERATED by scripts/update-docs-index.py"
    " -- do not edit below this line -->"
)
MARKER_END = (
    "<!-- AUTO-GENERATED by scripts/update-docs-index.py"
    " -- do not edit above this line -->"
)
SKIP_NAMES = frozenset({"index.md"})


def is_nav_page(name: str) -> bool:
    lower = name.lower()
    return lower == "index.md" or lower.endswith("index.md") or name.startswith("_")


def parse_frontmatter(text: str) -> dict[str, object] | None:
    """Parse a simple key: value frontmatter block. No nested YAML."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    data: dict[str, object] = {}
    for line in lines[1:]:
        stripped = line.strip()
        if stripped == "---":
            return data
        if not stripped or stripped.startswith("#"):
            continue
        if ":" not in stripped:
            return None
        key, raw = stripped.split(":", 1)
        key = key.strip()
        raw = raw.strip()
        if raw.startswith("[") and raw.endswith("]"):
            inner = raw[1:-1].strip()
            items = [
                item.strip().strip("\"'")
                for item in inner.split(",")
                if item.strip()
            ]
            data[key] = items
        else:
            data[key] = raw.strip("\"'")
    return None


def _skip_description_line(stripped: str) -> bool:
    if not stripped or stripped.startswith(("#", ">", "|", "<!--")):
        return True
    if stripped.startswith(("```", "~~~")):
        return True
    if stripped.startswith(("- ", "* ", "+ ")):
        return True
    if re.match(r"^\d+\.\s", stripped):
        return True
    if set(stripped) <= set("|-: "):
        return True
    if re.match(r"^\*\*[^*]+\*\*:?\s*$", stripped):
        return True
    if stripped.endswith(":") and len(stripped) < 40:
        return True
    return False


def derive_description(text: str) -> str:
    """First prose paragraph after frontmatter. Skips lists, quotes, tables, fences."""
    lines = text.splitlines()
    start = 0
    if lines and lines[0].strip() == "---":
        closed = False
        for idx, line in enumerate(lines[1:], 1):
            if line.strip() == "---":
                start = idx + 1
                closed = True
                break
        if not closed:
            return ""
    in_fence = False
    collected: list[str] = []
    for line in lines[start:]:
        stripped = line.strip()
        if stripped.startswith(("```", "~~~")):
            in_fence = not in_fence
            if collected:
                break
            continue
        if in_fence or _skip_description_line(stripped):
            if collected:
                break
            continue
        if not collected and (line[:1] in " \t" or stripped[:1].islower()):
            continue
        collected.append(stripped)
        para = " ".join(collected)
        if len(para) >= 80 and para.endswith("."):
            break
        if len(para) >= 160:
            break
    para = re.sub(r"\s+", " ", " ".join(collected)).strip()
    para = re.sub(r"\*\*([^*]+)\*\*", r"\1", para)
    para = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"\1", para)
    para = re.sub(r"`([^`]+)`", r"\1", para)
    if len(para) > 160:
        cut = para[:160]
        dot = cut.rfind(". ")
        if dot >= 60:
            para = cut[: dot + 1]
        else:
            para = cut.rsplit(" ", 1)[0]
    return para


def collect_docs(docs_dir: Path) -> list[dict[str, object]]:
    entries: list[dict[str, object]] = []
    for path in sorted(docs_dir.rglob("*.md")):
        if is_nav_page(path.name):
            continue
        rel_path = path.relative_to(docs_dir).as_posix()
        text = path.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)
        if fm is None:
            print(f"Warning: {rel_path} has no frontmatter, skipping.", file=sys.stderr)
            continue
        title = str(fm.get("title") or "").strip()
        if not title:
            print(f"Warning: {rel_path} has no title, skipping.", file=sys.stderr)
            continue
        desc = fm.get("description", "")
        if isinstance(desc, list):
            desc = " ".join(str(part) for part in desc)
        desc = str(desc).strip()
        if not desc:
            desc = derive_description(text)
        keywords = fm.get("keywords", [])
        if isinstance(keywords, str):
            keywords = [k.strip() for k in keywords.strip("[]").split(",") if k.strip()]
        elif isinstance(keywords, list):
            keywords = [str(k).strip() for k in keywords if str(k).strip()]
        else:
            keywords = []
        order_raw = fm.get("order", 99)
        try:
            order = int(order_raw)  # type: ignore[arg-type]
        except (TypeError, ValueError):
            print(
                f"Warning: {rel_path} has non-numeric order {order_raw!r}, using 99.",
                file=sys.stderr,
            )
            order = 99
        entries.append(
            {
                "rel_path": rel_path,
                "title": title,
                "description": desc,
                "keywords": keywords,
                "order": order,
            }
        )
    entries.sort(key=lambda e: (int(e["order"]), str(e["rel_path"])))
    return entries


def build_docs_list(entries: list[dict[str, object]]) -> str:
    lines: list[str] = []
    for entry in entries:
        line = f"- [{entry['title']}]({entry['rel_path']})"
        desc = str(entry["description"])
        if desc:
            line += f" -- {desc}"
        lines.append(line)
    return "\n".join(lines)


def build_keywords_line(entries: list[dict[str, object]]) -> str:
    seen: dict[str, str] = {}
    for entry in entries:
        kws = entry["keywords"]
        if not isinstance(kws, list):
            continue
        for kw in kws:
            key = str(kw).lower().strip()
            if key and key not in seen:
                seen[key] = str(kw).strip()
    return ", ".join(seen.values())


def replace_marked_section(text: str, replacement: str) -> str:
    lines = text.splitlines(keepends=True)
    starts = [i for i, line in enumerate(lines) if MARKER_START in line]
    ends = [i for i, line in enumerate(lines) if MARKER_END in line]
    if len(starts) != 1 or len(ends) != 1:
        raise ValueError(
            "docs/INDEX.md must contain exactly one start marker and one end marker "
            f"(found {len(starts)} start, {len(ends)} end)"
        )
    start_idx, end_idx = starts[0], ends[0]
    if start_idx >= end_idx:
        raise ValueError("start marker must appear before end marker in docs/INDEX.md")
    out = lines[: start_idx + 1]
    out.append("\n")
    if replacement:
        out.append(replacement)
        out.append("\n")
    out.append("\n")
    out.extend(lines[end_idx:])
    return "".join(out)


def replace_keywords_section(text: str, keywords: str) -> str:
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    in_keywords = False
    for line in lines:
        if line.strip() == "## Keywords":
            out.append(line)
            out.append("\n")
            if keywords:
                out.append(keywords)
                out.append("\n")
            in_keywords = True
            continue
        if in_keywords:
            if line.startswith("#"):
                in_keywords = False
                out.append("\n")
                out.append(line)
            continue
        out.append(line)
    return "".join(out)


def regenerate_index(index_path: Path, entries: list[dict[str, object]]) -> str:
    text = index_path.read_text(encoding="utf-8")
    text = replace_marked_section(text, build_docs_list(entries))
    return replace_keywords_section(text, build_keywords_line(entries))


def main(argv: list[str]) -> int:
    check_only = "--check" in argv
    if not DOCS_DIR.is_dir():
        print(f"Error: {DOCS_DIR}/ directory not found.", file=sys.stderr)
        return 1
    if not INDEX_FILE.is_file():
        print(f"Error: {INDEX_FILE} not found.", file=sys.stderr)
        return 1
    entries = collect_docs(DOCS_DIR)
    if not entries:
        print(f"Error: no titled docs found in {DOCS_DIR}/.", file=sys.stderr)
        return 1
    try:
        new_content = regenerate_index(INDEX_FILE, entries)
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    if check_only:
        current = INDEX_FILE.read_text(encoding="utf-8")
        if current != new_content:
            print(
                "Error: docs/INDEX.md is stale. "
                "Run scripts/update-docs-index.py to update.",
                file=sys.stderr,
            )
            return 1
        print(f"docs/INDEX.md is up to date ({len(entries)} docs).")
        return 0
    INDEX_FILE.write_text(new_content, encoding="utf-8")
    print(f"Regenerated {INDEX_FILE} ({len(entries)} docs indexed).")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
